### ISSUE TITLE
Noteable issues/changes during walkthroughs

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-3-course#10]
As folks take the course, please log your stuff here :) I will plan to address before the big group of new hires is onboarded!

**Comment by hcorson-dosch** [comment]
Tiny typo in Issue 6 - Splitters:
> Add a code to subset the rows in oldest_active_sites based on the branching variable, state_abb. Remember that oldest_active_sites has a column called state_cd containing the state abbreviations. Hint: go peek at the first line of the function get_site_data() in 1_fetch/src/get_site_data.R.

"Add a code" should be "Add code"

**Comment by hcorson-dosch** [comment]
In the 4th comment on the Appliers Issue (number 8) , the bot says:
> To help you assess your pipeline, here's what I would have put in that comment:

And then pastes:
* an image from one of the new plots in 3_visualize/out,
* a printout of the first 10 lines of tally_IL, and

but does not paste in this:
* a copy of the image shown by tar_visnetwork().

**Comment by hcorson-dosch** [comment]
In the Scale Up issue, after setting up and building the temperature pipeline, the bot prompts the taker to provide the following in a comment:
> When everything has run successfully, use a comment to share the images from timeseries_KY.png, timeseries_VT.png, and data_coverage.png. Include any observations you want to share about the build.

But we can't provide a timeseries of temperature for Vermont b/c we'd just been asked to remove VT from the temperature pipeline earlier in the activity:
> Remove 'VT' and 'GU' from the states target in _targets.R. It turns out that NWIS returns errors for these two states/territories for temperature, so we'll just skip them.

**Comment by lindsayplatt** [comment]
^ Yes, intentional but maybe not the best way to introduce that idea? Could just pick a different state and still have the next point be about how VT is still there, or could prompt by saying `...share the images from timeseries_KY.png and data_coverage.png. Peruse the other filenames available in that folder and then include any observations ...`

**Comment by lindsayplatt** [comment]
To fix the missing visnetwork image, I am going to use @hcorson-dosch's image so that I don't have to get my pipeline back to this state to regenerate :) 

![image](https://user-images.githubusercontent.com/13220910/127886177-4c632f4f-67a9-4a81-9758-7f317d7c72b6.png)
