### ISSUE TITLE
Replace image for conceptual branching

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-3-course#3]
A more refined version of this: 

![image](https://user-images.githubusercontent.com/13220910/119727606-1c77ee80-be38-11eb-89ed-c1f7803ceb50.png)

**Comment by aappling-usgs** [comment]
Is targets going to let you put the state abbrevs first in the branch names? I think for both static and dynamic branching, the branch name is a step/pattern prefix and a value name or hash suffix, respectively, right?

I like the idea of thinking about it in the order of tasks and then steps, so I think I'm suggesting the minor modification that the final column should have reordered rows and swapped prefix/suffix:
```
download_WI
download_MN
download_MI
tally_WI
tally_MN
tally_MI
plot_WI
plot_MN
plot_MI
```

**Comment by lindsayplatt** [comment]
Speaking of branching images ... I am going to use this one in one of the issues and need a URL!

![image](https://user-images.githubusercontent.com/13220910/119854642-daea5080-bed6-11eb-9c64-a4bfab5d437a.png)

**Comment by lindsayplatt** [comment]
polished version (editable SVG will be available in repo)

![branching_diagram](https://user-images.githubusercontent.com/13220910/125487324-fe9f0204-80ec-4d06-b751-ebf434eec64c.png)
